// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDg7JseqkMMTuPPRpH5aSEuFOOYRigVugg',
    appId: '1:577446149836:web:75aa93ae97c761b0ed4c69',
    messagingSenderId: '577446149836',
    projectId: 'tasty-dinery',
    authDomain: 'tasty-dinery.firebaseapp.com',
    storageBucket: 'tasty-dinery.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB3gDM-H-mKIpMBELE7Tpw82-lXH98eUSY',
    appId: '1:577446149836:android:96336aff3c7fb4aeed4c69',
    messagingSenderId: '577446149836',
    projectId: 'tasty-dinery',
    storageBucket: 'tasty-dinery.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAJ3eL5tzyshjoNUZDQ72VMAmb1MtBD6y0',
    appId: '1:577446149836:ios:07e21e78756318dbed4c69',
    messagingSenderId: '577446149836',
    projectId: 'tasty-dinery',
    storageBucket: 'tasty-dinery.appspot.com',
    androidClientId: '577446149836-rdjbdpjcg4e2hs5t79p1rkl2n561v812.apps.googleusercontent.com',
    iosClientId: '577446149836-n3v3j8ppodut0p42l45q4smu1324ksvn.apps.googleusercontent.com',
    iosBundleId: 'com.example.tastyDinery',
  );
}
